### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by TravisTorch** [BlueWhaleRobot/xqserial_server#2]
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "xiaoqiang_log"
  with any of the following names:

    xiaoqiang_logConfig.cmake
    xiaoqiang_log-config.cmake

  Add the installation prefix of "xiaoqiang_log" to CMAKE_PREFIX_PATH or set
  "xiaoqiang_log_DIR" to a directory containing one of the above files.  If
  "xiaoqiang_log" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  xqserial_server/CMakeLists.txt:14 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/travis/robot/build/CMakeFiles/CMakeOutput.log".
See also "/home/travis/robot/build/CMakeFiles/CMakeError.log".

**Comment by Jetson999** [comment]
you should `git  clone https://github.com/BluewhaleRobot/xiaoqiang_log` comper

**Comment by Jetson999** [comment]
你们可能还会遇到 galileo_serial_server
git clone https://github.com/BluewhaleRobot/galileo_serial_server.git

**Comment by TravisTorch** [comment]
> 你们可能还会遇到 galileo_serial_server
> git clone https://github.com/BluewhaleRobot/galileo_serial_server.git
好的  我试下
么么哒

**Comment by Dullyter** [comment]
我按照评论克隆了GitHub上的xiaoqiang_log和galileo_serial_server到我的src文件夹中，编译也可以通过，但是按照readme文件直接运行launch文件报错了，错误如下：
[ERROR] [1596089436.528297339]: Open /dev/ttyUSB001 failed.
[ERROR] [1596089436.531008240]: Exception: open: No such file or directory
[motor_driver-1] process has died [pid 10539, exit code 1, cmd /home/hwh/catkin_ws_xiaoqiang/devel/lib/xqserial_server/xqserial_server __name:=motor_driver __log:=/home/hwh/.ros/log/522dfd3e-d22b-11ea-a68f-000c29ac4633/motor_driver-1.log].
log file: /home/hwh/.ros/log/522dfd3e-d22b-11ea-a68f-000c29ac4633/motor_driver-1*.log
请问是咋回事儿

**Comment by Dullyter** [comment]
这是需要实际连接一个机器人才能运行么？

**Comment by Dullyter** [comment]
另外， "galileo_serial_server/GalileoStatus.h"这个文件我在galileo_serial_server的include文件夹里没有找到啊

**Comment by randoms** [comment]
这个是机器人的驱动程序，是要有机器人才能用的。`galileo_serial_server/GalileoStatus.h`这个文件是根据消息文件自动生成的， 到你的工作空间里面的devel文件夹里面找。

**Comment by Dullyter** [comment]
> 这个是机器人的驱动程序，是要有机器人才能用的。`galileo_serial_server/GalileoStatus.h`这个文件是根据消息文件自动生成的， 到你的工作空间里面的devel文件夹里面找。

多谢解答

**Comment by Jetson999** [comment]
> 这是需要实际连接一个机器人才能运行么？
是的，错误现实没有对应的设备

**Comment by Jetson999** [comment]
注意:同一工作空间

**Comment by Dullyter** [comment]
> 注意:同一工作空间

谢谢解答

**Comment by Dullyter** [comment]
> 注意:同一工作空间

谢谢解答
不过还想再厚脸皮问一下，工作空间该用哪个
