### ISSUE TITLE
如何使用此驱动控制机器人？

### ISSUE THREAD

**Issue by HanCHWang** [BlueWhaleRobot/xqserial_server#3]
这个马达驱动文件是怎么驱动机器人的？我没有找到机器人的xacro文件，也没有找到驱动编译的.so插件文件。

**Comment by randoms** [comment]
这个驱动程序要保证机器人上有我们的驱动器才行 [驱动器](http://www.bwbot.org/zh-cn/products/hub-motor-driver)
驱动器安装在机器人上之后，这个程序会通过驱动器控制机器人运动。
