### ISSUE TITLE
BW-DR03驱动盒应该使用哪个分支下的驱动

### ISSUE THREAD

**Issue by zhAlpha** [BlueWhaleRobot/xqserial_server#5]
目前的ros功能包驱动在BW-DR02下可以正常工作，但换了新的BW-DR03驱动盒则不能正常前进后退，请问是什么

**Comment by haquebd** [comment]
I just bought a BW-DR03 driver. Do you have a wiring diagram for a pair of hub motors in English? Do I need to calibrate motors before using the ROS package to manage it?

**Comment by randoms** [comment]
02和03协议是一样的。先用mtools工具验证一下03是否能正常工作。以及里面的参数是不是和02一致
