### ISSUE TITLE
Wiring Diagram or full documentation in English ?

### ISSUE THREAD

**Issue by haquebd** [BlueWhaleRobot/xqserial_server#6]
I just bought a BW-DR03 driver. Do you have a wiring diagram for a pair of hub motors in English? Do I need to calibrate motors before using the ROS package to manage it?

**Comment by randoms** [comment]
Sorry we only have Chinese documents right now. It's avaliable [here](https://doc.bwbot.org/en/books-online/mtools-doc/). You have to config the driver with mtools.exe before using this package.

**Comment by haquebd** [comment]
can you help to translate to English the options written in Chinese in this Mtool panel
![panel](https://user-images.githubusercontent.com/56286962/178561898-b06c791b-f312-4085-bbc6-2a8299019d49.png)
?

**Comment by randoms** [comment]
I'm working on the translations. Mtools with English translation might be published tomorrow.

**Comment by randoms** [comment]
The documents and software were updated. 

[English Doc](https://doc.bwbot.org/en/books-online/mtools-doc-en/)

[Driver tools](https://www.bwbot.org/s/ZXvUPR)

**Comment by haquebd** [comment]
What is the best email address or Whatsapp to get quotations and partnerships?

**Comment by randoms** [comment]
As I know you already have the wechat of our staff. Since this is irrelevant to the issue, I will close this issue. If you have further questions please contract us via wechat.

**Comment by randoms** [comment]
As I know you already have the wechat of our staff. Since this is irrelevant to the issue, I will close this issue. If you have further questions please contract us via wechat.
